version: '3.8'

services :
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: coldtea
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: vdbdictionary
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080