package de.coldtea.verborum.msuser.common.mapper;

import de.coldtea.verborum.msuser.vault.dto.VaultEntryRequestDTO;
import de.coldtea.verborum.msuser.vault.dto.VaultEntryResponseDTO;
import de.coldtea.verborum.msuser.vault.entity.VaultEntry;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface VaultEntryMapper {

    // Multi-param: vaultEntryId is generated by the service and userId comes from the path, so
    // neither is on the request DTO (same shape as ms_dictionary's WordMapper.toWord).
    @Mapping(source = "vaultEntryId", target = "vaultEntryId")
    @Mapping(source = "userId", target = "userId")
    VaultEntry toVaultEntry(String vaultEntryId, String userId, VaultEntryRequestDTO vaultEntryRequestDTO);

    VaultEntryResponseDTO toVaultEntryResponseDTO(VaultEntry vaultEntry);
}
